SELECT TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) AS MONTH, CAR_ID, COUNT(TO_CHAR(START_DATE, 'FMMM')) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
           WHERE TO_CHAR(START_DATE, 'MM') IN ('08', '09', '10')
           GROUP BY CAR_ID
           HAVING COUNT(CAR_ID) >= 5) -- 8~10월 사이 총 대여횟수가 5회이상인 자동차 중
AND TO_CHAR(START_DATE, 'MM') IN ('08', '09', '10') -- 8~10월 사이로 지정하지 않으면 다른 월도 출력될 수 있음
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')), CAR_ID
HAVING COUNT(TO_CHAR(START_DATE, 'FMMM')) > 0
ORDER BY 1, 2 DESC