SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U JOIN USED_GOODS_BOARD B
ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE' -- 상태가 DONE인
GROUP BY U.USER_ID, U.NICKNAME -- 유저 별로 그룹
HAVING SUM(B.PRICE) >= 700000 -- 총 판매 금액이 70만원 이상인
ORDER BY SUM(B.PRICE) -- 오름차순 출력