SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R -- 멤버와 리뷰 조인
USING(MEMBER_ID) JOIN -- [멤버id 리뷰개수등수] 테이블과 조인
(SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) RANKING
 FROM REST_REVIEW
GROUP BY MEMBER_ID) X
USING(MEMBER_ID)
WHERE X.RANKING = 1
ORDER BY 3, 2