def solution(msg):
    global dic
    answer = []
    dic = {}
    for i in range(65, 65+26): # 아스키 코드를 문자로 변환해서 딕셔너리에 저장
        dic[chr(i)] = i-64
    cnt = 27 # 새로운 색인번호를 카운트
    idx = 0 # 문자열 시작점을 가리키는 인덱스
    while idx < len(msg):
        # 현재 문자열을 출력
        for i in range(len(msg)-idx, -1, -1):
            if msg[idx:idx+i] in dic.keys(): # 현재 문자열이 사전에 있으면
                answer.append(dic[msg[idx:idx+i]]) # 정답 배열에 현재 문자열에 해당하는 인덱스 추가
                nowstr = msg[idx:idx+i] # 현재 문자열 저장
                nowend = idx+i # 현재 문자열의 끝인덱스 저장
                break
            
        if nowend < len(msg): # 현재 문자열 다음에 문자가 남아있으면
            if msg[idx:nowend+1] not in dic.keys(): # 현재문자열+다음문자 가 딕셔너리에 없으면
                dic[msg[idx:nowend+1]] = cnt # 새로운 인덱스와 함께 저장
                cnt += 1 # 인덱스 번호 +1
        idx += len(nowstr) # 문자열 시작점 가리키는 인덱스를 현재 문자열 길이만큼 이동
    return answer

print(solution("THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS"))
# print(dic)